### ISSUE TITLE
MapClaims are not compatible with RegisteredClaims

### ISSUE THREAD

**Issue by SzekeresB** [golang-jwt/jwt#137]
Hello!

I'm new to this jwt stuff and I have a question.

A linter error pointed me to `RegisteredClaims`:
`SA1019: jwt.StandardClaims is deprecated: Use RegisteredClaims instead for a forward-compatible way to access registered claims in a struct.`
and noticed the following: 

The `MapClaims`
```go
// MapClaims is a claims type that uses the map[string]interface{} for JSON decoding.
// This is the default claims type if you don't supply one
type MapClaims map[string]interface{}
```
has the following function:
```go
// VerifyExpiresAt compares the exp claim against cmp (cmp <= exp).
// If req is false, it will return true, if exp is unset.
func (m MapClaims) VerifyExpiresAt(cmp int64, req bool) bool
```

It looks like `RegisteredClaims` does not implement the `MapClaims` interface:
```go
// VerifyExpiresAt compares the exp claim against cmp (cmp <= exp).
// If req is false, it will return true, if exp is unset.
func (c *RegisteredClaims) VerifyExpiresAt(cmp time.Time, req bool) bool {
```
while the `StandardClaims` does implement it.
```go
// VerifyExpiresAt compares the exp claim against cmp (cmp <= exp).
// If req is false, it will return true, if exp is unset.
func (c *StandardClaims) VerifyExpiresAt(cmp int64, req bool) bool {
```

What is the `MapClaims` alternative for `RegisteredClaims`, is there any plan to introduce one?

**Comment by oxisto** [comment]
I am not quite sure what exactly you want to achieve, but `MapClaims` is not an interface, it is basically an alias for a generic hash map (`map[string]interface{}`). Interfaces in Go defined "contracts" for functions that need to be implemented. As far as I am aware, there is no such interface in our library that requires a `VerifyExpiresAt(cmp int64, req bool) bool`. We do have a `Claims` interface, but this only requires claims to have a `Valid` function.

The implementation of `RegisteredClaims`'s `VerifyExpiresAt` intentionally differs from `StandardClaims` because of the fact that the "old" struct does not support float-based time values, as required per JWT RFC. Therefore we chose to go the `time.Time` route to compare time values.

**Comment by SzekeresB** [comment]
Hello @oxisto !

It looks like I was quick on the trigger. I figured out where it went wrong on my side.

So one of my test cases used `MapClaims` as `StandardClaims` to validate the expiry field, and they worked so far because the `StandardClaims` could be replaced by `MapClaims` a generic hash map (`map[string]interface{}`) as they both have the `VerifyExpiresAt(cmp int64, req bool) bool` function.
But as I transitioned to the `RegisteredClaims` the tc broke.

Thanks for the fast reply to my question! I'm closing this issue.
