### ISSUE TITLE
Is there a ParserOption equivalent?

### ISSUE THREAD

**Issue by sergeybykov** [golang-jwt/jwt#142]
I can't seem to fine `ParserOption` and and a set of options that were introduced in [this PR](https://github.com/dgrijalva/jwt-go/pull/331).

Specifically, we use `WithAudience` and `WithoutAudienceValidation` in our code. Is there a different way to do this after migration or `ParserOption` functionality should be added to this repo?

**Comment by oxisto** [comment]
We originated from the original v3 instead of the (experimental) v4 branch. This is why we have not fully implemented the parser options or rather the validation options yet. See #16 and also #139

**Comment by sergeybykov** [comment]
I see. Does this mean that audience is not currently enforced?
We had to upgrade to v4.0.0-preview1 of github.com/dgrijalva/jwt-go/ a few months ago to ensure that audience is validated and enforced. Should we wait with migration until validators are ported then?

**Comment by oxisto** [comment]
> I see. Does this mean that audience is not currently enforced?

No, its the other way around, audience checking is always enforced (equivalent to `WithAudience`) and you cannot currently turn it off.

> We had to upgrade to v4.0.0-preview1 of github.com/dgrijalva/jwt-go/ a few months ago to ensure that audience is validated and enforced. Should we wait with migration until validators are ported then?

If you refer to https://github.com/advisories/GHSA-w73w-5m7g-f7qc, that has been fixed in the 3.2.1 release of this library and is also fixed in the 4.x.x version of this library. The only functionality that is missing is turning parts of the validation off (for various reasons) or adding more custom validation options.

**Comment by sergeybykov** [comment]
Perfect. Thank you, @oxisto!
