### ISSUE TITLE
Add member to golang-jwt organization

### ISSUE THREAD

**Issue by mfridman** [golang-jwt/jwt#154]
I propose to add @oxisto as a Member to the golang-jwt organization. They've been helping out quite a bit.

We originally started with a short list of folks that were involved with the upstream project:

https://github.com/orgs/golang-jwt/people 

But as time goes on we should (cautiously) add folks that are actively involved with a track record to ensure the health of the project. Any objections @ripienaar @lggomez @Waterdrips ?

**Comment by lggomez** [comment]
Not from my part, it's been long overdue IMO and he has an extensive security background which also comes in handy 😄 . Unfortunately I've not been able to contribute these past months due to some personal issues which make spend less time on a pc outside working hours but these days i'm trying to move on some stale PRs he's also been taking a look at

**Comment by mfridman** [comment]
Invitation sent. Big thank you to @oxisto for helping out with the project.
