### ISSUE TITLE
Trim slash at the end of issuer URLs prior to verifying issuer

### ISSUE THREAD

**Issue by miparnisari** [golang-jwt/jwt#159]
Probably a noob question, but:

https://github.com/golang-jwt/jwt/blob/78a18c0808520e53b59e7a4396915430d51749f1/claims.go#L264

Since both `iss` and `cmp` are URLs... is it possible to trim `/` at the end of both strings prior to making the comparison? Otherwise I have to call this function twice on my end.

**Comment by oxisto** [comment]
> Probably a noob question, but:
> 
> https://github.com/golang-jwt/jwt/blob/78a18c0808520e53b59e7a4396915430d51749f1/claims.go#L264
> 
> Since both `iss` and `cmp` are URLs... is it possible to trim `/` at the end of both strings prior to making the comparison? Otherwise I have to call this function twice on my end.

Tricky question. This is more of a question with relation to RFC compliance behaviour rather than the usage of this library. There are two relevant sections in the RFC:

- https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1: `The processing of this claim is generally application specific.`. Meaning that what the issuer value means to the application is generally up to the application. It is also not necessarily a URL (more specifically it is a `StringOrURI`). It can either be a simple string or URL, however, if it contains a `:` character, it must be treated as a URL.
- https://datatracker.ietf.org/doc/html/rfc7519#section-2. The definition of `StringOrURI` states that `StringOrURI values are compared as case-sensitive strings with no transformations or canonicalizations applied.`. This would be a strong argument for NOT trimming the `/` at the end.

Sorry for not giving you a clear yes / no anwser on this one.

**Comment by lggomez** [comment]
@oxisto beat me to it, altough with the perspective from the JWT RFC IMO it should be clear that the comparison cannot be altered as we would change the comparison semantics

Per https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.4 (URI RFC):
```

 Substantial effort to reduce the incidence of false negatives is
   often cost-effective for web spiders.  Therefore, they implement even
   more aggressive techniques in URI comparison.  For example, if they
   observe that a URI such as

      http://example.com/data

   redirects to a URI differing only in the trailing slash

      http://example.com/data/

   they will likely regard the two as equivalent in the future.  This
   kind of technique is only appropriate when equivalence is clearly
   indicated by both the result of accessing the resources and the
   common conventions of their scheme's dereference algorithm (in this
   case, use of redirection by HTTP origin servers to avoid problems
   with relative references).
```

As the JWT states that the claims are URIs instead of URLs I think the answer is clear. Would we be talking about the latter, the answer would be more tricky to get (as I couldn't find any mention to the treatment of trailing slashes on the URL RFC)
