### ISSUE TITLE
proxy.golang.org say the latest version is v3.2.0, not v4.3.0

### ISSUE THREAD

**Issue by ahuigo** [golang-jwt/jwt#169]
https://proxy.golang.org/github.com/dgrijalva/jwt-go/@latest
https://goproxy.io/github.com/dgrijalva/jwt-go/@v/list

{"Version":"v3.2.0+incompatible","Time":"2018-03-08T23:13:08Z"}

```
$ go get -u github.com/dgrijalva/jwt-go@v4.3.0
go get: github.com/dgrijalva/jwt-go@v4.3.0: invalid version: unknown revision v4.3.0
```

**Comment by ahuigo** [comment]
I should use `go get  github.com/golang-jwt/jwt`

**Comment by wushaobo** [comment]
@ahuigo 
I see the problem still there. The latest version on proxies of `github.com/golang-jwt/jwt` is still v3 rather than v4.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/491264/170453373-1e621dcd-23b5-4385-bf35-97408a5e5bc6.png">

How could we use the latest released version ?

**Comment by wushaobo** [comment]
I got the answer. 
Use `github.com/golang-jwt/jwt/v4` rather than `github.com/golang-jwt/jwt` for latest version.
