### ISSUE TITLE
key is of invalid type for "typ": "JWS"

### ISSUE THREAD

**Issue by mrichman** [golang-jwt/jwt#193]
My JWT has a header like this:

```json
{
  "typ": "JWS",
  "alg": "RS256",
  "kid": "9167337"
}
```

Note this is is `JWS` not `JWT`.

When I call `jwt.Parse()` on it like this, I get `token.Valid` is false:

```go
token, err := jwt.Parse(authToken, func(token *jwt.Token) (interface{}, error) {
        return []byte("AllYourBase"), nil
})
```

The error is "key is of invalid type". Am I doing something wrong here, or is JWS unsupported?

**Comment by oxisto** [comment]
Well, your algorithm is `RS256`, indicating the use of an asymmetric key, such as RSA. The key you provide is a symmetric key, e.g. used in HS256. Therefore it indicates that you are using using an invalid key type. This is not a JWS issue, rather than a mix up in key algorithms.

I recommend having a look at https://github.com/MicahParks/keyfunc, which can use used as a keyfunc in the `jwt.Parse` function call in order to fetch the public key needed for verification from a JWS endpoint.

**Comment by oxisto** [comment]
Ah sorry, lack of sleep here, you were talking about JWS, not JWKS; JWS is not fully supported; however since JWT is a subset of JWS, some things should work. The issue about the key type mixup in your example still remains.

**Comment by MicahParks** [comment]
The second argument to [`jwt.Parse`](https://pkg.go.dev/github.com/golang-jwt/jwt/v4#Parse) is a [`jwt.Keyfunc`](https://pkg.go.dev/github.com/golang-jwt/jwt/v4#Keyfunc). This function, returns a `interface{}` and an `error`. The type of the `interface{}` being returned is dependent on the type of the cryptographic key used to sign the JWT being parsed.

It looks like you are using an RSA key, so the type returned for the `interface{}` should be a [`*rsa.PublicKey`](https://pkg.go.dev/crypto/rsa#PublicKey). When `[]byte("AllYourBase")` is returned instead, I believe HMAC is assumed due to the type. Since the code snippets in the original issue don't seem to contain an RSA key, you'll need to find the _public_ RSA key associated with the JWTs being signed and transform that into the correct Go type. If you have the exponent and modulus, you can use [this file](https://github.com/MicahParks/keyfunc/blob/master/rsa.go) as an example.

If you're juggling multiple keys outside of a JWKS, it may be helpful to check out the `github.com/MicahParks/keyfunc` package mentioned in another comment. There is support for "given keys" which helps create a [`jwt.Keyfunc`](https://pkg.go.dev/github.com/golang-jwt/jwt/v4#Keyfunc) in a more strongly typed way. Note it's essentially a map of a JWT's `kid` to its cryptographic key. If you only have one RSA key you're concerned with, an inline function returning the correct type is a simpler solution.

**Comment by mrichman** [comment]
@MicahParks Thanks, but how would I convert `[]byte("AllYourBase")` to `*rsa.PublicKey`? How would I know if I have the exponent and modulus? Is that part of the JWT itself or the identity provider?

**Comment by MicahParks** [comment]
If your key is truly `[]byte("AllYourBase")`, then I'm concerned it's not an RSA key. I would think it's some sort of symmetric key, like HMAC. (RSA uses "asymmetric" cryptography whereas technologies like HMAC or AES are "symmetric". Asymmetric cryptography relies on "public" and "private" keys. In the case of verifying a JWT, the public key is needed. Symmetric cryptography relies on a shared secret, it only uses a single "private" key.)

If you are using `[]byte("AllYourBase")` as an example for a `[]byte` of an RSA _public_ key that had been read into memory, that depends on the format of the data stored within the `[]byte`. If your organization is not using a JWKS, then it's possible you've received an x509 certificate. There's numerous examples of how to decode that x509 certificate to a `*rsa.PublicKey`, [here's one from StackOverflow](https://stackoverflow.com/a/33088784/14797322). It's not a perfect example, so don't copy/paste it, always check errors.

If I were you, I'd first identify what you are given. From the outside, that looks like an HMAC secret key, but if you're certain it's an RSA _public_ key, you need to determine the encoding so you can search for an answer specific to that encoding.

**Comment by mrichman** [comment]
When I paste my issued JWT into jwt.io, I see this:
<img width="531" alt="Screen Shot 2022-05-13 at 5 49 15 PM" src="https://user-images.githubusercontent.com/11228/168393933-59c515b7-8c49-4926-a839-b9b144e1e7f8.png">

**Comment by MicahParks** [comment]
Since an RSA key was used to sign the JWT, if you want to verify it, the public key needs to be found, decoded, then transformed into an `*rsa.PublicKey`.

I'm unable to identify the encoding for `[]byte("AllYourBase")`, so I can't be of any further help in the process. (It's likely not the RSA public key associated with the JWT.) Once the encoding is identified, searching for an example that decodes a public key encoded the same way, that should lead you down the right path.

**Comment by MicahParks** [comment]
It depends on what is meant by "validate".

I'm assuming this means read the JWT's payload, then do something with it, without verifying the token's signature.

If that's the case, there's this method: https://pkg.go.dev/github.com/golang-jwt/jwt/v4#Parser.ParseUnverified

Make sure to always verify JWT cryptographic signatures in production.

I've made an example for you:
```go
package main

import (
	"errors"
	"fmt"
	"log"

	"github.com/golang-jwt/jwt/v4"
)

var (
	// ErrInvalidClaims indicates that the JWT's claims were invalid.
	ErrInvalidClaims = errors.New("the JWT's claims were invalid")
)

// MyClaims are the expected JWT claims.
//
// It implements the jwt.Claims interface.
type MyClaims struct {
	Sub  string `json:"sub"`
	Name string `json:"name"`
	Iat  int    `json:"iat"`
}

// Valid implements the jwt.Claims interface.
func (m MyClaims) Valid() error {
	log.Println("Validating claims...")
	if m.Sub == "" || m.Name == "" || m.Iat == 0 {
		return fmt.Errorf("JWT claims contained a zero value: %w", ErrInvalidClaims)
	}
	return nil
}

func main() {
	tokenString := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
	claims := MyClaims{}

	parser := jwt.NewParser()
	token, _, err := parser.ParseUnverified(tokenString, &claims) // Note the & operator for the claims variable.
	if err != nil {
		log.Fatalf("Failed to parse JWT.\nError: %s", err)
	}

	if token.Valid { // This will always be false, since it was parsed unverified.
		log.Println("Token has valid cryptographic signature.")
	} else {
		log.Println("Token has invalid cryptographic signature.")
	}

	// Token claims will not be validated during the above step. If you'd like them validated, make sure to call the
	// method.
	if claims.Valid() != nil {
		log.Println("Token claims invalid.")
	} else {
		log.Println("Token claims valid.")
	}

	// The claims can also be accessed via a field on the token, but it must be type asserted.
	tokenClaims, ok := token.Claims.(*MyClaims)
	if !ok {
		log.Fatalf("Failed token claims type assertion.\nError: %s", err)
	}
	log.Println(claims.Sub, claims.Name, claims.Iat)
	log.Println(tokenClaims.Sub, tokenClaims.Name, tokenClaims.Iat)
}
```

**Comment by mrichman** [comment]
Thank you, this is really helpful. What I think I need to do is to verify the signature using JWKS. I have that URL from my IdP. Since I'm doing this for every API call coming in, it would seem computationally expensive to call out to that JWKS URL for every API call. Do you know of an example where the JWKS can be cached to avoid this?

**Comment by MicahParks** [comment]
I do! I wrote a package that extends this one for JWKS. You can find it here: https://github.com/MicahParks/keyfunc

Here's my recommended example to follow: https://github.com/MicahParks/keyfunc/blob/master/examples/recommended_options/main.go

There are more examples in that directory, like for AWS Cognito, which I've seen is a common use case: https://github.com/MicahParks/keyfunc/blob/master/examples/aws_cognito/main.go

**Comment by mrichman** [comment]
This is perfect, thank you! In the case of `token.Valid` returning `false`, is there a way to get a reason code?

**Comment by MicahParks** [comment]
It looks like the only assignment to that field in the code base is here:
https://github.com/golang-jwt/jwt/blob/6e2ab4291f1aa2205dc9e407e2d23c21c3886e0d/parser.go#L104-L107

Which is in the `ParseWithClaims` method.

It looks like this field is assigned `true` if there is no validation error for _both_ the claims and the JWT's signature.

If you need to know which of the two it is, I think the easiest way to determine the reason is to call `token.Claims.Valid()`. If that method call does not return an error, then the JWT's signature was invalid. If that method returns an error, then it could be both the JWT's claims and signature are invalid. Figuring out if it was _only_ the invalid JWT claims would involve copying the functionality of this snippet:
https://github.com/golang-jwt/jwt/blob/6e2ab4291f1aa2205dc9e407e2d23c21c3886e0d/parser.go#L97-L102

**Comment by mrichman** [comment]
Okay, this is now working great. I can validate/verify the token using JWKS. However, when the token expires, I'm dead in the water. I need to somehow on my client side work this out and obtain a new token so I can pass that into my API call header.
