### ISSUE TITLE
VerifyExpiresAt returns false when not required and exp is empty

### ISSUE THREAD

**Issue by nrgraham23** [golang-jwt/jwt#239]
The VerifyExpiresAt function returns false when it is not required and the exp token is an empty string because it returns `false` if there is not a match in the switch statement: https://github.com/golang-jwt/jwt/blob/main/map_claims.go#L58

Based on the comment on the method and the [old](https://github.com/dgrijalva/jwt-go/blob/master/map_claims.go#L44) version of this method, it seems like this is a bug.

**Comment by oxisto** [comment]
Sorry for the long delay. Somehow this issue slipped my radar. The function was intentionally changed in this PR: https://github.com/golang-jwt/jwt/pull/40

The current implementation is a little bit better in terms of security, because an "empty string" is not valid for `exp`. According to the RFC, `exp` must be a date timestamp in a JSON number. Therefore, we decided to return false in the end of the switch statement in case someone is trying to validate a token with `exp` being anything else but a JSON number as an additional safeguard.
