### ISSUE TITLE
int64 type conversion fails on claims

### ISSUE THREAD

**Issue by mohanavel15** [golang-jwt/jwt#253]
code : 
```go
package main

import (
	"fmt"
	"time"

	"github.com/golang-jwt/jwt"
)

func main() {
	secret_key := []byte("Hello, world")

	token := jwt.New(jwt.SigningMethodHS256)

	claims := token.Claims.(jwt.MapClaims)
	claims["iat"] = time.Now().Unix()

	tokenString, _ := token.SignedString(secret_key)

	new_token, _ := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("there was an error")
		}
		return secret_key, nil
	})

	new_claims, _ := new_token.Claims.(jwt.MapClaims)

	iat := new_claims["iat"].(int64)

	fmt.Println(iat)
}
```

error : 
```
panic: interface conversion: interface {} is float64, not int64
```

`time.Now().Unix()` returns int64 so it should be int64, not float64

**Comment by oxisto** [comment]
Numbers in JSON are always float64.`MapClaims` uses the raw json encoding functionality of Golang and therefore your `iat` will be a float64.

There are two options to consider:
1) You can use the ParserOption `WithJSONNumber`, this forces the Go json package to use `json.Number` instead of `float64` and you can then use this special type to convert to int again (see https://pkg.go.dev/encoding/json#Number.Int64)
2) You can use the `RegisteredClaims` struct, this one has a special type `NumericDate` (see the examples), this type basically handles converting between the JSON float and a `time.Time` struct

**Comment by mohanavel15** [comment]
Thanks.
